# Generated by Django 2.1.1 on 2018-09-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=True)),
            ],
        ),
    ]
