# Generated by Django 2.1.1 on 2018-09-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
